import type { MetadataRoute } from 'next';

// Single PWA manifest source (served as /manifest.webmanifest).
// Icon PNGs are generated by scripts/generate-pwa-icons.mjs — do not
// hand-edit sizes here without regenerating public/icons/*.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'FuelUp — Calorie & Fitness Tracker',
    short_name: 'FuelUp',
    description: 'Track calories, workouts, body metrics, and habits all in one app.',
    start_url: '/',
    scope: '/',
    display: 'standalone',
    orientation: 'portrait',
    background_color: '#0b0b0c',
    theme_color: '#0b0b0c',
    categories: ['health', 'fitness', 'lifestyle'],
    icons: [
      { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
      { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
      { src: '/icons/maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  };
}
